#!/usr/bin/env ruby

masks = [
  nil,
  0b110_100_000,
  0b111_010_000,
  0b011_001_000,
  0b100_110_100,
  0b010_111_010,
  0b001_011_001,
  0b000_100_110,
  0b000_010_111,
  0b000_001_011
]

states = [[ARGV[0].to_i(2), []]]

loop do
  board, path = states.shift

 if board == 0
   puts path.join
   break
 end

  (1..9).each do |move|
    unless path.include?(move)
      states << [board ^ masks[move], path + [move]]
    end
  end
end
