#!/usr/bin/env ruby

MASKS = [
  nil,
  0b110_100_000,
  0b111_010_000,
  0b011_001_000,
  0b100_110_100,
  0b010_111_010,
  0b001_011_001,
  0b000_100_110,
  0b000_010_111,
  0b000_001_011
]

board = ARGV[0].to_i(2)

0.upto(9) do |length|
  (1..9).to_a.combination(length) do |moves|
    if moves.map { |m| MASKS[m] }.reduce(board, :^).zero?
      puts moves.join
      exit
    end
  end
end
